### ISSUE TITLE
add a `max_retries` provider option

### ISSUE THREAD

**Issue by scross01** [hashicorp/terraform-provider-opc#7]
A `max_retries` attribute is needed on the provider to set the maximum number of times an API call is retried, to handle cases where requests encounter transient failures, similar to https://www.terraform.io/docs/providers/aws/#max_retries

Default value would be `1`

**Comment by tombuildsstuff** [comment]
Migrated this to the new repo: https://github.com/terraform-providers/terraform-provider-opc/issues/4
